-- ============================================================
-- Snowflake Analytics Schema
-- SQLite 스키마를 Snowflake로 마이그레이션
-- ============================================================
-- 실행 전 Snowflake 콘솔에서:
-- 1. CREATE DATABASE STREAMING_ANALYTICS;
-- 2. CREATE SCHEMA STREAMING_ANALYTICS.ANALYTICS;
-- 3. USE DATABASE STREAMING_ANALYTICS;
-- 4. USE SCHEMA ANALYTICS;
-- ============================================================

-- ========================================
-- 1. 플랫폼 유저 (스트리머 + 시청자 통합)
-- ========================================
CREATE TABLE IF NOT EXISTS PLATFORM_USERS (
  ID NUMBER AUTOINCREMENT PRIMARY KEY,

  -- 플랫폼 식별
  PLATFORM VARCHAR(20) NOT NULL DEFAULT 'soop',
  PLATFORM_USER_ID VARCHAR(100) NOT NULL,

  -- 기본 정보
  USERNAME VARCHAR(100) NOT NULL,
  NICKNAME VARCHAR(200),
  PROFILE_IMAGE VARCHAR(500),

  -- 유저 타입
  IS_STREAMER BOOLEAN DEFAULT FALSE,
  IS_PARTNER BOOLEAN DEFAULT FALSE,

  -- 스트리머 전용 정보 (JSON)
  STREAMER_DATA VARIANT,

  -- 통계 스냅샷
  FOLLOWER_COUNT NUMBER DEFAULT 0,
  SUBSCRIBER_COUNT NUMBER DEFAULT 0,
  FAN_COUNT NUMBER DEFAULT 0,

  -- 타임스탬프
  FIRST_SEEN_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  LAST_SEEN_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),

  UNIQUE(PLATFORM, PLATFORM_USER_ID)
);


-- ========================================
-- 2. 방송 세션 (라이브 단위)
-- ========================================
CREATE TABLE IF NOT EXISTS BROADCASTS (
  ID NUMBER AUTOINCREMENT PRIMARY KEY,

  -- 플랫폼/방송 식별
  PLATFORM VARCHAR(20) NOT NULL DEFAULT 'soop',
  BROADCAST_ID VARCHAR(100) NOT NULL,

  -- 스트리머 연결
  STREAMER_ID NUMBER REFERENCES PLATFORM_USERS(ID),
  STREAMER_USERNAME VARCHAR(100),

  -- 방송 정보
  TITLE VARCHAR(500),
  CATEGORY VARCHAR(200),
  SUB_CATEGORY VARCHAR(200),
  TAGS VARIANT,

  -- 시간
  STARTED_AT TIMESTAMP_NTZ NOT NULL,
  ENDED_AT TIMESTAMP_NTZ,
  DURATION_SECONDS NUMBER,

  -- 집계 통계
  PEAK_VIEWERS NUMBER DEFAULT 0,
  AVG_VIEWERS FLOAT DEFAULT 0,
  TOTAL_UNIQUE_VIEWERS NUMBER DEFAULT 0,
  TOTAL_CHAT_COUNT NUMBER DEFAULT 0,
  TOTAL_DONATION_AMOUNT NUMBER DEFAULT 0,

  -- 상태
  IS_LIVE BOOLEAN DEFAULT TRUE,

  UNIQUE(PLATFORM, BROADCAST_ID)
);


-- ========================================
-- 3. 방송 스냅샷 (5분 단위 상태 기록)
-- ========================================
CREATE TABLE IF NOT EXISTS BROADCAST_SNAPSHOTS (
  ID NUMBER AUTOINCREMENT PRIMARY KEY,
  BROADCAST_ID NUMBER NOT NULL REFERENCES BROADCASTS(ID),

  -- 스냅샷 시각 (5분 단위 정각)
  SNAPSHOT_AT TIMESTAMP_NTZ NOT NULL,

  -- 시청자 수
  TOTAL_VIEWERS NUMBER DEFAULT 0,
  PC_VIEWERS NUMBER DEFAULT 0,
  MOBILE_VIEWERS NUMBER DEFAULT 0,

  -- 변경 추적
  TITLE VARCHAR(500),
  CATEGORY VARCHAR(200),

  UNIQUE(BROADCAST_ID, SNAPSHOT_AT)
);


-- ========================================
-- 4. 시청 기록 (핵심 테이블!)
-- ========================================
CREATE TABLE IF NOT EXISTS VIEWING_RECORDS (
  ID NUMBER AUTOINCREMENT PRIMARY KEY,

  -- 누가
  VIEWER_ID NUMBER NOT NULL REFERENCES PLATFORM_USERS(ID),
  VIEWER_USERNAME VARCHAR(100),

  -- 어디서
  BROADCAST_ID NUMBER NOT NULL REFERENCES BROADCASTS(ID),
  STREAMER_ID NUMBER REFERENCES PLATFORM_USERS(ID),

  -- 언제 (5분 단위 스냅샷 시각)
  SNAPSHOT_AT TIMESTAMP_NTZ NOT NULL,

  -- 시청자 상태
  IS_SUBSCRIBER BOOLEAN DEFAULT FALSE,
  IS_FAN BOOLEAN DEFAULT FALSE,

  -- 중복 방지
  UNIQUE(VIEWER_ID, BROADCAST_ID, SNAPSHOT_AT)
)
CLUSTER BY (SNAPSHOT_AT, BROADCAST_ID);


-- ========================================
-- 5. 후원 기록
-- ========================================
CREATE TABLE IF NOT EXISTS DONATIONS (
  ID NUMBER AUTOINCREMENT PRIMARY KEY,

  -- 후원자
  SENDER_ID NUMBER REFERENCES PLATFORM_USERS(ID),
  SENDER_USERNAME VARCHAR(100),
  SENDER_NICKNAME VARCHAR(200),

  -- 수신자 (스트리머)
  RECEIVER_ID NUMBER REFERENCES PLATFORM_USERS(ID),
  RECEIVER_USERNAME VARCHAR(100),

  -- 방송 정보
  BROADCAST_ID NUMBER REFERENCES BROADCASTS(ID),

  -- 후원 유형
  DONATION_TYPE VARCHAR(50) NOT NULL,

  -- 금액
  ITEM_COUNT NUMBER DEFAULT 0,
  AMOUNT_KRW NUMBER DEFAULT 0,

  -- 메시지
  MESSAGE VARCHAR(1000),

  -- 구독 전용
  SUBSCRIPTION_MONTHS NUMBER,

  -- 시각
  DONATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
CLUSTER BY (DONATED_AT);


-- ========================================
-- 6. 시청 세션 (집계 테이블)
-- ========================================
CREATE TABLE IF NOT EXISTS VIEWING_SESSIONS (
  ID NUMBER AUTOINCREMENT PRIMARY KEY,

  VIEWER_ID NUMBER NOT NULL REFERENCES PLATFORM_USERS(ID),
  BROADCAST_ID NUMBER NOT NULL REFERENCES BROADCASTS(ID),
  STREAMER_ID NUMBER REFERENCES PLATFORM_USERS(ID),

  -- 연속 시청 구간
  SESSION_START TIMESTAMP_NTZ NOT NULL,
  SESSION_END TIMESTAMP_NTZ,

  -- 시청 시간
  DURATION_SECONDS NUMBER DEFAULT 0,
  SNAPSHOT_COUNT NUMBER DEFAULT 0,

  -- 동시 시청 정보
  AVG_CONCURRENT_STREAMS FLOAT DEFAULT 1
);


-- ========================================
-- 7. 모니터링 설정
-- ========================================
CREATE TABLE IF NOT EXISTS MONITORING_CONFIG (
  ID NUMBER AUTOINCREMENT PRIMARY KEY,

  CONFIG_KEY VARCHAR(100) NOT NULL UNIQUE,
  CONFIG_VALUE VARCHAR(500) NOT NULL,

  DESCRIPTION VARCHAR(500),

  UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 기본 설정 삽입
MERGE INTO MONITORING_CONFIG AS target
USING (
  SELECT 'max_websocket_connections' AS CONFIG_KEY, '100' AS CONFIG_VALUE, '최대 동시 WebSocket 연결 수' AS DESCRIPTION
  UNION ALL SELECT 'min_viewers_threshold', '100', 'WebSocket 연결 기준 최소 시청자 수'
  UNION ALL SELECT 'snapshot_interval_seconds', '300', '스냅샷 주기 (초)'
  UNION ALL SELECT 'api_polling_interval_seconds', '300', 'API 폴링 주기 (초)'
) AS source
ON target.CONFIG_KEY = source.CONFIG_KEY
WHEN NOT MATCHED THEN INSERT (CONFIG_KEY, CONFIG_VALUE, DESCRIPTION) VALUES (source.CONFIG_KEY, source.CONFIG_VALUE, source.DESCRIPTION);


-- ========================================
-- 8. 모니터링 대상 (수동 등록)
-- ========================================
CREATE TABLE IF NOT EXISTS MONITORING_TARGETS (
  ID NUMBER AUTOINCREMENT PRIMARY KEY,

  PLATFORM VARCHAR(20) NOT NULL DEFAULT 'soop',
  TARGET_USERNAME VARCHAR(100) NOT NULL,

  PRIORITY NUMBER DEFAULT 0,
  IS_ACTIVE BOOLEAN DEFAULT TRUE,
  NOTE VARCHAR(500),

  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),

  UNIQUE(PLATFORM, TARGET_USERNAME)
);


-- ========================================
-- 9. 일별 집계 통계
-- ========================================
CREATE TABLE IF NOT EXISTS DAILY_STATS (
  ID NUMBER AUTOINCREMENT PRIMARY KEY,

  STAT_DATE DATE NOT NULL,
  PLATFORM VARCHAR(20) NOT NULL DEFAULT 'soop',

  USER_ID NUMBER REFERENCES PLATFORM_USERS(ID),
  USER_TYPE VARCHAR(20) NOT NULL,

  -- 스트리머 통계
  BROADCAST_COUNT NUMBER DEFAULT 0,
  TOTAL_BROADCAST_SECONDS NUMBER DEFAULT 0,
  PEAK_VIEWERS NUMBER DEFAULT 0,
  AVG_VIEWERS FLOAT DEFAULT 0,
  UNIQUE_VIEWERS NUMBER DEFAULT 0,
  TOTAL_DONATIONS_RECEIVED NUMBER DEFAULT 0,

  -- 시청자 통계
  STREAMS_WATCHED NUMBER DEFAULT 0,
  TOTAL_WATCH_SECONDS NUMBER DEFAULT 0,
  UNIQUE_STREAMERS_WATCHED NUMBER DEFAULT 0,
  TOTAL_DONATIONS_SENT NUMBER DEFAULT 0,

  UNIQUE(STAT_DATE, USER_ID, USER_TYPE)
)
CLUSTER BY (STAT_DATE);


-- ========================================
-- 10. 수집 작업 로그
-- ========================================
CREATE TABLE IF NOT EXISTS COLLECTION_LOGS (
  ID NUMBER AUTOINCREMENT PRIMARY KEY,

  JOB_TYPE VARCHAR(50) NOT NULL,
  STARTED_AT TIMESTAMP_NTZ NOT NULL,
  COMPLETED_AT TIMESTAMP_NTZ,

  STATUS VARCHAR(20) DEFAULT 'running',
  RECORDS_PROCESSED NUMBER DEFAULT 0,
  ERROR_MESSAGE VARCHAR(2000),

  DETAILS VARIANT
);


-- ========================================
-- 11. 방송 통계 (5분 단위 집계)
-- ========================================
CREATE TABLE IF NOT EXISTS BROADCAST_STATS_5MIN (
  ID NUMBER AUTOINCREMENT PRIMARY KEY,
  BROADCAST_ID NUMBER NOT NULL REFERENCES BROADCASTS(ID),

  SNAPSHOT_AT TIMESTAMP_NTZ NOT NULL,

  VIEWER_COUNT NUMBER DEFAULT 0,
  SUBSCRIBER_COUNT NUMBER DEFAULT 0,
  FAN_COUNT NUMBER DEFAULT 0,

  SUBSCRIBER_RATIO FLOAT DEFAULT 0,
  FAN_RATIO FLOAT DEFAULT 0,

  CHAT_COUNT NUMBER DEFAULT 0,
  UNIQUE_CHATTERS NUMBER DEFAULT 0,

  DONATION_COUNT NUMBER DEFAULT 0,
  DONATION_AMOUNT NUMBER DEFAULT 0,

  UNIQUE(BROADCAST_ID, SNAPSHOT_AT)
)
CLUSTER BY (SNAPSHOT_AT);


-- ========================================
-- 12. 방송 변경 이력
-- ========================================
CREATE TABLE IF NOT EXISTS BROADCAST_CHANGES (
  ID NUMBER AUTOINCREMENT PRIMARY KEY,
  BROADCAST_ID NUMBER NOT NULL REFERENCES BROADCASTS(ID),

  FIELD_NAME VARCHAR(50) NOT NULL,
  OLD_VALUE VARCHAR(500),
  NEW_VALUE VARCHAR(500),

  CHANGED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


-- ========================================
-- 13. 채팅 메시지 통계
-- ========================================
CREATE TABLE IF NOT EXISTS CHAT_MESSAGES (
  ID NUMBER AUTOINCREMENT PRIMARY KEY,
  BROADCAST_ID NUMBER NOT NULL REFERENCES BROADCASTS(ID),

  SENDER_ID NUMBER REFERENCES PLATFORM_USERS(ID),
  SENDER_USERNAME VARCHAR(100) NOT NULL,
  SENDER_NICKNAME VARCHAR(200),

  MESSAGE_LENGTH NUMBER DEFAULT 0,

  SENT_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
CLUSTER BY (SENT_AT);


-- ============================================================
-- Snowflake 특화 기능: 뷰 생성
-- ============================================================

-- 스트리머별 시청자 통계 뷰
CREATE OR REPLACE VIEW STREAMER_VIEWER_STATS AS
SELECT
  pu.USERNAME AS STREAMER,
  pu.NICKNAME AS STREAMER_NICKNAME,
  COUNT(DISTINCT vr.VIEWER_ID) AS UNIQUE_VIEWERS,
  COUNT(DISTINCT vr.BROADCAST_ID) AS BROADCASTS,
  COUNT(*) AS TOTAL_VIEWING_RECORDS,
  MAX(b.PEAK_VIEWERS) AS MAX_PEAK_VIEWERS
FROM VIEWING_RECORDS vr
JOIN PLATFORM_USERS pu ON vr.STREAMER_ID = pu.ID
JOIN BROADCASTS b ON vr.BROADCAST_ID = b.ID
GROUP BY pu.USERNAME, pu.NICKNAME;


-- 시청자별 시청 통계 뷰
CREATE OR REPLACE VIEW VIEWER_WATCH_STATS AS
SELECT
  pu.USERNAME AS VIEWER,
  pu.NICKNAME AS VIEWER_NICKNAME,
  COUNT(DISTINCT vr.STREAMER_ID) AS UNIQUE_STREAMERS,
  COUNT(DISTINCT vr.BROADCAST_ID) AS BROADCASTS_WATCHED,
  COUNT(*) AS TOTAL_VIEWING_RECORDS,
  MIN(vr.SNAPSHOT_AT) AS FIRST_SEEN,
  MAX(vr.SNAPSHOT_AT) AS LAST_SEEN
FROM VIEWING_RECORDS vr
JOIN PLATFORM_USERS pu ON vr.VIEWER_ID = pu.ID
GROUP BY pu.USERNAME, pu.NICKNAME;


-- 겹시청자 분석 뷰 (A → B 스트리머 공유 시청자)
CREATE OR REPLACE VIEW OVERLAP_VIEWERS AS
SELECT
  pu_a.USERNAME AS STREAMER_A,
  pu_b.USERNAME AS STREAMER_B,
  COUNT(DISTINCT vr_a.VIEWER_ID) AS SHARED_VIEWERS
FROM VIEWING_RECORDS vr_a
JOIN VIEWING_RECORDS vr_b ON vr_a.VIEWER_ID = vr_b.VIEWER_ID
  AND vr_a.STREAMER_ID < vr_b.STREAMER_ID  -- 중복 방지
JOIN PLATFORM_USERS pu_a ON vr_a.STREAMER_ID = pu_a.ID
JOIN PLATFORM_USERS pu_b ON vr_b.STREAMER_ID = pu_b.ID
GROUP BY pu_a.USERNAME, pu_b.USERNAME
HAVING COUNT(DISTINCT vr_a.VIEWER_ID) > 10
ORDER BY SHARED_VIEWERS DESC;


-- 일별 수집 요약 뷰
CREATE OR REPLACE VIEW DAILY_COLLECTION_SUMMARY AS
SELECT
  DATE_TRUNC('DAY', SNAPSHOT_AT) AS COLLECTION_DATE,
  COUNT(DISTINCT VIEWER_ID) AS UNIQUE_VIEWERS,
  COUNT(DISTINCT BROADCAST_ID) AS ACTIVE_BROADCASTS,
  COUNT(DISTINCT STREAMER_ID) AS ACTIVE_STREAMERS,
  COUNT(*) AS TOTAL_RECORDS
FROM VIEWING_RECORDS
GROUP BY DATE_TRUNC('DAY', SNAPSHOT_AT)
ORDER BY COLLECTION_DATE DESC;
